config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes do
    resources :ingredients
    resources :procedures
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
   belongs_to :recipe

   validates :name, presence: true
   validates :quantity, presence: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
   belongs_to :recipe

   validates :description, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :procedures

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.ingredients.create(ingredient_params)
    redirect_to edit_recipe_path(@recipe)
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :unit_of_measure, :quantity)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.procedures.create(procedure_params)
    redirect_to edit_recipe_path(@recipe)
  end

  private
  def procedure_params
    params.require(:procedure).permit(:step, :description)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
     @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.valid?
      redirect_to edit_recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
     @recipe = Recipe.find(params[:id])
     @ingredient = Ingredient.new
     @procedure = Procedure.new
  end

  def add_ingredient

  end

  private   
  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REMV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb

<div class='img-construction'><%= image_tag 'construction.jpg' %></div>
<h1> under construction </h1>
<h2> for quiz 1 purposes only </h2>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg">
      <h2> <%= @recipe.name %>  </h2>
    </div>
  </div>
  <div class="row"> 
    <div class="col-lg">
        <%= @recipe.description %> 
    </div>
  </div>
  <hr/>
  <h6> Ingredients</h6>
  <div class="container ingredient">
    <div class="float-right" style="padding-right: 10px">
      <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
        Add Ingredient
      </button>
    </div>
    <% @recipe.ingredients.each do |ingredient| %>
      <div class="row" style="width: 400px">
        <div class="col-sm"> <%= ingredient.quantity.to_i %> </div>
        <div class="col-sm col-4"> <%= ingredient.unit_of_measure %> </div>
        <div class="col-sm col-8"> <%= ingredient.name %> </div>
    </div>
    <% end %>
  </div>
  <hr/>
  <h6> Procedures</h6>
  <div class="float-right" style="padding-right: 10px">
    <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#procedureModal">
      Add Procedure
    </button>
  </div>
  <div class="container procedure">
    <% @recipe.procedures.each do |procedure| %>
     <div class="row">
      <div class="col-sm-1"> <%= procedure.step.to_i %> </div>
       <div class="col-sm-8"> <%= procedure.description %> </div>
       <div class="col-sm-2"></div>
     </div>
    <% end %>
  </div>
</div>

<!-- Comment Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add an Ingredient</h4>
      </div>
      <%= simple_form_for @ingredient, url: recipe_ingredients_path(@recipe) do |f| %>
        <div class="modal-body">
          <%= f.input :quantity, label: "Quantity" %>
          <%= f.input :unit_of_measure, label: "Unit of Measure" %>
          <%= f.input :name, label: "Name" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add Ingredient", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Comment Modal -->
<div class="modal fade" id="procedureModal" tabindex="-1" role="dialog" aria-labelledby="procedureModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Procedure</h4>
      </div>
      <%= simple_form_for @procedure, url: recipe_procedures_path(@recipe) do |f| %>
        <div class="modal-body">
          <%= f.input :step, label: "Step" %>
          <%= f.input :description, label: "Description" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add Procedure", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<h1>Cookbook</h1>
</br>
<hr>
<div class="float-right" style="padding-right: 10px">
  <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
    Add a Recipe
  </button>
</div>
<div class="center-div">
  <% @recipes.each do |recipe| %>
    <div class="card" style="width: 50rem;">
      <div class="card-body">
        <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe) %></h5>
        <p class="card-text"><%= recipe.description %></p>
      </div>
    </div>
    <br/>
  <% end %>
</div>

<!-- Comment Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Recipe</h4>
      </div>
      <%= simple_form_for Recipe.new do |f| %>
        <div class="modal-body">
          <%= f.input :name, label: "Recipe" %>
          <%= f.input :description, label: "Description" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Recipe", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg">
      <h2> <%= @recipe.name %>  </h2>
    </div>
  </div>
  <div class="row"> 
    <div class="col-lg">
        <%= @recipe.description %> 
    </div>
  </div>
  <hr/>
  <h6> Ingredients</h6>
  <div class="container ingredient">
    <% @recipe.ingredients.each do |ingredient| %>
      <div class="row" style="width: 400px">
        <div class="col-sm"> <%= ingredient.quantity.to_i %> </div>
        <div class="col-sm col-4"> <%= ingredient.unit_of_measure %> </div>
        <div class="col-sm col-8"> <%= ingredient.name %> </div>
    </div>
    <% end %>
  </div>
  <hr/>
  <h6> Procedures</h6>
  <div class="container procedure">
    <% @recipe.procedures.each do |procedure| %>
     <div class="row">
      <div class="col-sm-1"> <%= procedure.step.to_i %> </div>
       <div class="col-sm-8"> <%= procedure.description %> </div>
       <div class="col-sm-2"></div>
     </div>
    <% end %>
  </div>
</div>